name: Style Checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    if: github.repository == 'nodejs/node-addon-api'
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
    - run: git branch -a
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: FORMAT_START=refs/remotes/origin/main npm run lint
